### ISSUE TITLE
Put all entries on graph but show specific entries labels on bottom axis 

### ISSUE THREAD

**Issue by galharth** [patrykandpatryk/vico#106] opened 2022-07-14 11:29 UTC
Let's say I have 100 entries, how can I put only labels for only part of them on the bottom axis? to show there only 0, 5, 10, 20 .. 100

**Comment by galharth** [comment] 2022-07-14 15:43
@patrykmichalik is there an option to scale down the size of the graph? not just to put empty strings? also weirdly when I use your example I see the graph but only no labels on the bottom axis except 0.0

**Comment by galharth** [comment] 2022-07-16 15:26
1. I'm talking about a line chart, I want to make the distance between 0.0 to 1.0 smaller, currently, there is a big distance between values on the bottom axis, the graph should look like sinus but I see only the beginning of the graph because there is a lot of float entries between 0.0 and 1.0 
![Screenshot_20220716-181654_FlowMD](https://user-images.githubusercontent.com/564274/179361137-1ea4e82c-0704-40ad-885c-891a17b9d3b7.png)


2.  As I check again, there is a weird bug that if I scroll the graph the bottom axis label appears only when I scroll at a specific point, in the first screenshot below you can see the label 1.0 but in the second screenshot below you can't see the label 1.0 although I suppose to see him (its the same area approximately)
![Screenshot_20220716-181749_FlowMD](https://user-images.githubusercontent.com/564274/179361240-2387ad1b-5d95-42fb-aa7d-dcbe70d8066a.png)
![Screenshot_20220716-182306_FlowMD](https://user-images.githubusercontent.com/564274/179361293-733fbd7f-aa5b-491a-b92e-2754859e9fbf.png)

**Comment by patrykmichalik** [comment] 2022-07-21 13:00
Apologies for the late reply.

1. You can control the segment width by editing the point size and spacing. However, if you significantly decrease the segment width, youʼll end up with a rather large number of ticks along the bottom axis, and additionally, there will be insufficient space for the labels. Iʼll speak to @Gowsky about how we could accommodate your use case, as Iʼve taken a look around a couple of apps and it appears to be relatively common. Iʼll keep you updated.
2. Would you be able to provide a minimal reproducible example? Cheers!

**Closed** 2022-08-08 17:34 UTC
Labels: enhancement

**Comment by raudonikis** [comment] 2023-02-14 15:02
Are there any plans to support custom labels? None of the provided options work for me, i need to display labels conditionally, depending on the amount of entries. Also there seem to be issues with truncation, even though there's plenty of space, the first label is not visible:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/46673448/218774950-573a5feb-c75d-43f3-b4cb-e3654f98e85c.png">

I am using Jetpack Compose, in this specific case there are 28 entries, and configuring the bottom axis like so:

```
return bottomAxis(
        guideline = null,
        axis = null,
        tick = null,
        label = defaultAxisLabel(),
        tickPosition = HorizontalAxis.TickPosition.Center(offset = 1, spacing = 5)
    )
```

I've also tried your suggestion with a ValueFormatter, but then no label is visible:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/46673448/218775746-833d30d8-9814-4565-8c4c-537ebfdeb24e.png">

**Comment by patrickmichalik** [comment] 2023-02-14 17:24
Hello! Regarding your first point, there is a significant amount of empty space on the right of the truncated label, but the label is centered, so if there’s insufficient space on the left, no amount of free space on the right will help. Would you expect the label to shift right in such an instance? About adjusting the label spacing based on the entry count, you should be able to read the size of the entry list and dynamically calculate the label spacing based on that.

**Comment by raudonikis** [comment] 2023-02-14 19:10
Hi
1. But the truncated text "..." takes more space than just "1", right? 😄 Not sure why there would not be enough space. I don't know what I would expect to be honest, shifting values right might introduce more issues.
2. My explanation might have been unclear, the spacing provided by the library does not suit my specific use case, since the spacing is not exactly the same between all labels, for example I need these labels: [1,5,10,15,20,25,28] when the entry count is 28 (for the month of february). Basically spacing - 5, but also show the 1st and last values.

**Comment by patrickmichalik** [comment] 2023-02-14 20:48
1. This is how truncation works, as peculiar as it may seem. If the label’s intrinsic width exceeds its maximum width, the label is truncated. But at some point, further truncation is impossible, and for short strings, it may occur that the truncated text is wider than the original text. Not all components are clipped to their maximum bounds, so even if the width of the ellipsis exceeds the maximum width for the label, the ellipsis may be fully visible. We’ll look into improving this. That said, it may be the case that the maximum width for the label is being improperly calculated, and truncation shouldn’t occur to begin with. Would you be able to provide a full minimal reproducible example for this? I’d then be able to confirm what’s happening.
2. Got it. We’d be happy to add such functionality. Could you open a dedicated issue?

**Comment by raudonikis** [comment] 2023-02-15 19:21
I've created a demo repository with the 2 cases I mentioned: by using the `TickPosition.Edge` with spacing, and by using a `ValueFormatter` to hide specific values, feel free to check it out -> https://github.com/raudonikis/VicoChartsDemo

**Comment by patrickmichalik** [comment] 2023-02-21 14:48
Thank you, @raudonikis! I’ve taken a closer look at this. The maximum label width is calculated correctly, and there does appear to be insufficient space for the first and last labels. Please note that axis labels have 4 dp of horizontal padding by default. If you were to reduce this to 0 dp, the first label would fit, as you can see below. However, there’d still be too little room for the last label.

![](https://user-images.githubusercontent.com/120058021/220375051-4797432f-0e2e-40e7-b083-7264aaec5cea.png)

It’s worth noting that the bounds of different axes don’t overlap. Here’s how far left and right the bottom axis can draw content:

![](https://user-images.githubusercontent.com/120058021/220377143-1cfb5833-4c94-40d9-a6b5-1ba816588cd8.png)
