### ISSUE TITLE
xAxis tick number

### ISSUE THREAD

**Issue by EzzPress** [patrykandpatryk/vico#145] opened 2022-10-26 21:08 UTC
Hi! Is it possible to adjust minor/major vertical gridlines to decrease their value?

**Comment by BrezPress** [comment] 2022-10-26 21:10
![Screenshot_20221027_0008461](https://user-images.githubusercontent.com/109756293/198138836-5e576554-a0af-4d9e-8320-4fe68d1c726c.png)

**Comment by patrykmichalik** [comment] 2022-10-27 14:23
Hello! The `HorizontalAxis.TickPosition.Center` constructor has a `spacing` parameter. The default value is 1. Once you change the value to _n_, ticks will be displayed every _n_ entries. This is demonstrated in the second sample chart. See [here](https://github.com/patrykandpatryk/vico/blob/master/sample/src/main/java/com/patrykandpatryk/vico/sample/chart/ColumnChart.kt#L71-L74) for the relevant code.

**Comment by EzzPress** [comment] 2022-10-30 21:17
Thank you for your tip! It works for me
![image](https://user-images.githubusercontent.com/109756293/198901878-edd468c1-5b41-444e-90d5-7b21c03d8827.png)
But my case is show upcoming data (1-10 dots per sec). 
In case when x-values of chart entry are Ints, grid is ok, when I use Floats the grid is gone and blinks sometimes.
![image](https://user-images.githubusercontent.com/109756293/198901990-abd4fa9e-c0b6-4499-8b04-3bdbca73bd9c.png)
Maybe I missed some initial settings?
```
private val entries: MutableList<FloatEntry> = MutableList(0) { FloatEntry(0f, 0f) }
    val producer = ChartEntryModelProducer(entries)
```

**Comment by patrykmichalik** [comment] 2022-10-31 15:58
I’m glad to hear that the `spacing` parameter did the trick. Regarding the grid issue, would you be able to provide a minimal reproducible example?

**Comment by EzzPress** [comment] 2022-11-01 20:04
on my way

**Comment by EzzPress** [comment] 2022-11-02 21:24
> I’m glad to hear that the `spacing` parameter did the trick. Regarding the grid issue, would you be able to provide a minimal reproducible example?

https://github.com/EzzPress/VicoExample

check the viewmodel comments in init function

**Comment by patrykmichalik** [comment] 2022-11-08 16:27
Cheers!

**Comment by EzzPress** [comment] 2022-12-05 21:17
> I’m glad to hear that the `spacing` parameter did the trick. Regarding the grid issue, would you be able to provide a minimal reproducible example?

Some updates - grid disappears when the new x value is not a divisor to the grid range. 
For example:
- 1f step for new chart values - ok
- 0.5f step for new chart values - ok
- 0.51f step for new chart values - grid fails

**Comment by patrykmichalik** [comment] 2022-12-08 08:51
Thanks for the update! At the moment, Vico doesn’t support entirely arbitrary distances between the _x_ values of entries, which is why the grid is misbehaving. _x_ values can be skipped, but a level of consistency is expected. For example, $(0,1,2,4)$ works, but $(0,0.49,1.23,5.34)$ causes issues. If you’d like to display entries with arbitrary _x_ values in an equidistant manner, you can use an `AxisValueFormatter` implementation (see [here](https://patrykandpatryk.com/vico/wiki/core-topics/custom-data-types)). We plan on adding support for arbitrarily spaced entries in the future (#112). In order to make things clearer, we’ll be looking into having an exception thrown when the _x_ step cannot be calculated (as is the case here).

**Comment by patrickmichalik** [comment] 2022-12-11 13:44
I’ve taken a closer look at the function responsible for calculating the _x_ step, and it would appear that instead of calculating the greatest common denominator of the _x_ values, it finds the pair of values with the smallest difference and treats said difference as the step, the assumption being that the smallest difference divides all other differences. It’d be preferable if the greatest common denominator were used, so I’ll be updating the function accordingly. Once this is done, the issue you’ve described will no longer occur. However, it’s worth noting that the greatest common denominator of 0.5 and 0.51 is 0.01, so if the set of _x_ values is (0, 0.5, 0.51), the grid will be correctly drawn, but there will be a large number of empty segments between the entry with an _x_ value of 0 and the entry with an _x_ value of 0.5. Therefore, a custom `AxisValueFormatter` implementation will still be the way to go as far as displaying entries with arbitrary _x_ values in an equidistant manner is concerned.

**Comment by patrickmichalik** [comment] 2022-12-18 11:42
Vico 1.6.1, which is now rolling out, introduces the changes described in my last comment. As it turns out, the direct cause of the issue with the bottom axis was that `HorizontalAxis` handled fractional _x_ values improperly. That too has been resolved. Consequently, I’ll be closing this issue. Thanks for your feedback!

**Closed by patrickmichalik** 2022-12-18 11:42 UTC
